### PR TITLE
Japanese translation files

### PR DESCRIPTION
**Pull request by Gedevan-Aleksizde**
* I misassigned one ID in my previous pull request, sorry.
* Japanese translation added. It could be helpful for Japanese Steam Workshop users.

### CODE REVIEW

**Comment by PajTajster** [comment]
Hey - sorry for no response. I'm working on new version where I've added new texts, I presume it'd be better to update those in this pull request. What do you think?

Misassigned ID i cherry-picked into new build (so you'll be listed as author), thanks for noticing that!

**Comment by Gedevan-Aleksizde** [comment]
It's up to you. I can also remake this after your new version. No problem even if so. It doesn't take much for me

**Comment by PajTajster** [comment]
Okay then - I will push out newest version, 2.7.0, then you can, if you want, upload more translations.

I think I will just release cloned, separate version for Steam Workshop then? As in, nexus mods will stay on master, whereas translation one will have it's own branch. It's so people will still have to download your translation mod from nexus, but in case of Steam Workshop it will be in one package, just as you described. :)

**Comment by Gedevan-Aleksizde** [comment]
It's best to include the translation files in both Nexus and Steam Workshop because I doubt the Vortex correctly installs the translation mods that require overwriting another mod. I won't claim authorship for this translation. However, I follow your decision. I should understand the difficulty of managing language files that you can't read.

**Comment by Gedevan-Aleksizde** [comment]
Now, this PR contains only Japanese translation files.

**Comment by Gedevan-Aleksizde** [comment]
Oops. I found another ID error.

**Comment by PajTajster** [comment]
> It's best to include the translation files in both Nexus and Steam Workshop because I doubt the Vortex correctly installs the translation mods that require overwriting another mod. I won't claim authorship for this translation. However, I follow your decision. I should understand the difficulty of managing language files that you can't read.

This is totally valid reason, I can include it in both. I was mostly looking into your translation files being downloaded separately. Translating isn't easy so credit is always due. I will add gratitude towards you on mod page.

Thanks for noticing ID typo!

**Pull request merged**
